spring.datasource.url=jdbc:mysql://z37udk8g6jiaqcbx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ozodhcz4aqsyymrf?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username=hzfsdkwfyeq3lpl5
spring.datasource.password=jprqcrzwlztu9x4i
